// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djxdbltjwqavzhpkrnzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqeGRibHRqd3FhdnpocGtybnpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NDk4MzgsImV4cCI6MjA3MTAyNTgzOH0.SmgRRtRC8H0oEP6LjEX-uK8PHjwHG3CdPDwO997Favo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

export const updatePremiumUiEnabled = async (userId: string, premiumUiEnabled: boolean) => {
  const { data, error } = await supabase
    .from('profiles')
    .update({ premiumuienabled: premiumUiEnabled })
    .eq('id', userId);

  if (error) {
    console.error('Error updating premium UI enabled status:', error);
    throw error;
  }
  return data;
};